CONTRIBUTING.md güncellendi
CodeFiction/typescript-book pull request #19
Opened 2017-01-29 11:25 UTC by mahmut-gundogdu

Skype ile 29.01.17 deki konuşulan çalışma şekline dair notları içerir.

2017-01-29 12:35 UTC, msusur requested changes

2017-01-29 12:35 UTC, msusur commented on CONTRIBUTING.md
> +- Öncelikle ingilizceye çevirdikten sonra iki farklı kişi gözden geçirecek. İki kişi onaylarsa merge edilecek. Pull requesti merge edecek kişi aynı isimle sonuna "gozden-gecirilecek" ekleyerek yeni b
`ingilizce'ye` i büyük olmali.

Pull requesti ==> Pull request'i

gozden ==> gözden

gecirilecek ==> geçirilecek

2017-01-29 12:35 UTC, msusur commented on CONTRIBUTING.md
> +- Atanmıs bir issue ile ilgili yardımcı olabilecekseniz issue sahibi ile iletişim geçilmeli.
Atanmıs ==> Atanmış

2017-01-29 13:29 UTC, UgurAldanmaz reviewed
Çeşitli öneri ve düzeltmeler.

2017-01-29 13:29 UTC, UgurAldanmaz commented on CONTRIBUTING.md
> +- Atanmıs bir issue ile ilgili yardımcı olabilecekseniz issue sahibi ile iletişim geçilmeli.
Takım dışından katılım gösterecek olan kişiler için assign etme işlemi geçerli değil. Yalnızca CodeFiction takımında yer alan kişiler kendini assign edebiliyor. Bu nedenle bu ifadenin biraz daha netleştirilmesine ihtiyaç var.

Önerim:

Çevirisi henüz yapılmamış olan bölümlere [issue listesinden](https://github.com/CodeFiction/typescript-book/issues) ulaşılabilir.
Katkıda bulunmak istediğiniz konuya yorum bırakarak son durumu sorabilirsiniz.

2017-01-29 13:29 UTC, UgurAldanmaz commented on CONTRIBUTING.md
> +- Çeviri yaparken birebir çeviriden ziyade okuyacak kişinin türkçe olarak anlayabileceği şekilde olmasını hedefliyoruz.
türkçe => Türkçe

2017-01-29 13:29 UTC, UgurAldanmaz commented on CONTRIBUTING.md
> +- Çeviri yaparken birebir çeviriden ziyade okuyacak kişinin türkçe olarak anlayabileceği şekilde olmasını hedefliyoruz.
Hedefimiz birebir çeviriden ziyade, bir Türk okuyucu için anlamlı cümlelerin oluşturulmasıdır.

2017-01-29 13:29 UTC, UgurAldanmaz commented on CONTRIBUTING.md
> +- Çeviri ile ilgili terimlerin ortak olarak olarak anlamlarının tutulduğu yer GLOSSARY.md dosyasıdır.
Teknik terimlerin çevirisinde bir bütünlük sağlamak amacı ile bir [sözlük](GLOSSARY.md) oluşturulmuştur. Lütfen çevirinizi yaparken bu sözlükte yer alan terimleri takip ediniz.

2017-01-30 07:12 UTC, mahmut-gundogdu commented
Ben düzelttim,commitledim. Şimdi tekrar mı Pr göndermeliyim? Ne yapmalıyım?

2017-01-30 08:39 UTC, UgurAldanmaz commented
Yeni bir PR açmana gerek yok. PR açtığın branch'e yapacağın her yeni commit otomatik olarak PR'ye dahil olacak.

2017-01-30 10:17 UTC, mahmut-gundogdu commented
o zaman 2 review 1 merge alayım lütfen.

2017-01-31 16:33 UTC, msusur approved these changes

2017-01-31 21:42 UTC, tugrulcan approved these changes
Eline sağlık. Birkaç markdown ile düzenlemeye çalıştım.

2017-02-01 09:54 UTC, merged