String Template cevirisi ve glossary guncellemesi
CodeFiction/typescript-book pull request #32
Opened 2017-01-30 23:53 UTC by ozgend

2017-01-31 14:34 UTC, onuar commented on docs/template-strings.md
> +Şablon string tanımının önüne (`tag` olarak isimlendirilen) fonksiyonları ekleyebilir ve ilgili şablon stringinin ön işlenmesini gerçekleştirerek buradan dönen sonucu kullanabilirsiniz.
String yabancı bir ifade olduğu için, sonrasında gelen ekleri apostrof ile ayırabiliriz. "String'inin" gibi.

2017-01-31 14:34 UTC, onuar commented on docs/template-strings.md
> +ES6 öncesi derlemede oluşturulan çıktı oldukça basit. Çok satırlı stringler kaçış karakterlilere çevirilir. String aradeğerleme ifadeleri *string birleştirme*ye dönüşür. Biçimlendirilmiş şablonlar no
"Çok satırlı stringler kaçış karakterlilere çevirilir"
Acaba burada "çevrilir" (become) ifadesi bir type convertion gibi algılanır mı diye düşündüm de. Tartışmaya açmak istedim.

2017-01-31 14:34 UTC, onuar commented on docs/template-strings.md
> +Bir programlama dilinde *çok satırlı stringler* ve *string aradeğerleme* kullanımlarının bulunması buyuk kolaylık sağlamaktadır. TypeScript sayesinde bunlar artık JavaScript ile kullanılabililir. Biç
buyuk > büyük

nası şaka ama.

2017-01-31 14:42 UTC, msusur commented on docs/template-strings.md
> +ES6 öncesi derlemede oluşturulan çıktı oldukça basit. Çok satırlı stringler kaçış karakterlilere çevirilir. String aradeğerleme ifadeleri *string birleştirme*ye dönüşür. Biçimlendirilmiş şablonlar no
Allah kimseyi "kacis karakterli" yapmasin, dinimiz amin.

2017-01-31 14:45 UTC, onuar commented on docs/template-strings.md
> +ES6 öncesi derlemede oluşturulan çıktı oldukça basit. Çok satırlı stringler kaçış karakterlilere çevirilir. String aradeğerleme ifadeleri *string birleştirme*ye dönüşür. Biçimlendirilmiş şablonlar no
Delikanlı developer'ın kitabında "kaçış karakterli" anlatılmaz. Bence bu kısmı çıkarabiliriz.

2017-01-31 14:46 UTC, msusur commented on docs/template-strings.md
> +ES6 öncesi derlemede oluşturulan çıktı oldukça basit. Çok satırlı stringler kaçış karakterlilere çevirilir. String aradeğerleme ifadeleri *string birleştirme*ye dönüşür. Biçimlendirilmiş şablonlar no
Saka bir yana ama kacis karakterinin Turkce'de hic bir anlami yok gibi geliyor bana :) Okuyucu olarak bu kitabi okudugumda cok kizardim :)

2017-01-31 14:47 UTC, onuar commented on docs/template-strings.md
> +ES6 öncesi derlemede oluşturulan çıktı oldukça basit. Çok satırlı stringler kaçış karakterlilere çevirilir. String aradeğerleme ifadeleri *string birleştirme*ye dönüşür. Biçimlendirilmiş şablonlar no
Glossary'de "çevirisi yapıldığında bozulan ifadeler" gibi bir bölüm bırakmıştım. O kısma açıklamasını yazıp, burada orjinal ifade kullanabiliriz. Tabii açıklamaya link vermek kaydı ile.

2017-02-01 17:15 UTC, msusur requested changes

2017-02-01 17:15 UTC, msusur commented on docs/template-strings.md
> +TypeScript'teki şablon stringler aşağıdaki kolaylığı sağlamakta:
`string'ler`

2017-02-01 17:37 UTC, ozgend commented on docs/template-strings.md
> +ES6 öncesi derlemede oluşturulan çıktı oldukça basit. Çok satırlı stringler kaçış karakterlilere çevirilir. String aradeğerleme ifadeleri *string birleştirme*ye dönüşür. Biçimlendirilmiş şablonlar no
kacis karakteri ifadesini escape karakteri olarak sozluge ekliyorum ve buradaki degisiklikleri ona gore duzenliyorum

2017-02-01 22:29 UTC, ozgend commented
gerekli duzeltmeler tamamlandi.

2017-02-02 13:12 UTC, msusur approved these changes

2017-02-02 13:12 UTC, merged