Update iterators.md
CodeFiction/typescript-book pull request #33
Opened 2017-01-31 08:29 UTC by vceylan

Aralardaki kısımları türkçeye, dilimin döndüğü kadar, çevirdim. Fakat kodarı aynen bıraktım çok anlaşılmayan kısmı yok diye düşündüm.

2017-01-31 10:58 UTC, msusur requested changes

2017-01-31 10:58 UTC, msusur commented on docs/iterators.md
> +Peki, iyi güzel, fakat daha da yararlı nasıl kullanabilir? ES6 [Symbol.iterator] `sembol` içeren *tekrarlanabilir protokol* tanımlar.
`Peki, iyi guzel de, daha da yararli nasil kullanilabilir?` daha iyi bir ceviri olur muydu?

2017-01-31 10:58 UTC, msusur commented on docs/iterators.md
> +Tekrar belirtmek gerekirse yineleyici bir TypeScript özelliği değildir.  Bu kod Iterator ve IteratorResult arayüzlerini açıkça uygulamadan da çalışabilir.
implement'in turkcesi uygulamak ama sanki burada anlami kaybediyoruz gibi geldi. okudugumda bir sey anlayamadigim icin ingilizcesini okuma ihtiyaci hissettim :(

2017-01-31 10:58 UTC, msusur commented on docs/iterators.md
> +Ne yazık ki bu tasarımla `frame.next()` çalışmaz ve bir takım işler eksikmiş gibi gözükür.
`Gozukur` yanlis kullanim degil ama ben `gorunur` tercih ederdim :)

2017-02-01 05:50 UTC, vceylan commented on docs/iterators.md
> +Tekrar belirtmek gerekirse yineleyici bir TypeScript özelliği değildir.  Bu kod Iterator ve IteratorResult arayüzlerini açıkça uygulamadan da çalışabilir.
O zaman, "Bu kod Iterator ve IteratorResult arayüzleri kullanılmadan da çalışabilir." dersek daha güzel olabilir.

2017-02-01 06:31 UTC, vceylan commented on docs/iterators.md
> +Peki, iyi güzel, fakat daha da yararlı nasıl kullanabilir? ES6 [Symbol.iterator] `sembol` içeren *tekrarlanabilir protokol* tanımlar.
Olabilir ben orda direk çeviriye kafa yorarak düşündüm o yüzden fakat vs kullanma gereği duydum :)

2017-02-01 11:20 UTC, msusur requested changes

2017-02-01 11:20 UTC, msusur commented on docs/iterators.md
> +Tekrar belirtmek gerekirse yineleyici bir TypeScript özelliği değildir.  Bu kod Iterator ve IteratorResult arayüzlerini açıkça uygulamadan da çalışabilir.
fazladan bir bosluk var sanirim 🍶

2017-02-02 05:48 UTC, vceylan commented on docs/iterators.md
> +Tekrar belirtmek gerekirse yineleyici bir TypeScript özelliği değildir.  Bu kod Iterator ve IteratorResult arayüzlerini açıkça uygulamadan da çalışabilir.
Bu kısmı aşağıdaki gibi yapmıştım aslında ama orda bir sıkıntı olmuş:

`Bu kod Iterator ve IteratorResult arayüzleri kullanılmadan da çalışabilir.`

Bu şekilde olabilir mi?

2017-02-02 13:12 UTC, msusur approved these changes

2017-02-02 13:12 UTC, merged