Contributing kurallarına git mesajlarını ekliyorum
CodeFiction/typescript-book pull request #34
Opened 2017-02-01 10:10 UTC by msusur

2017-02-01 19:42 UTC, onuar commented on CONTRIBUTING.md
> + # Katkıda bulunmak isteyenler için Bilgilendirme:
Başlıklarda ya tüm kelimelerin ilk harfinin büyük ya da sadece ilk kelimenin baş harfinin büyük olmasını tercih etmeliyiz.

2017-02-01 19:42 UTC, onuar commented on CONTRIBUTING.md
>  ### Yerelleştirme İşlemi Aşamaları
Başlık seçimine göre tekrar bakmak gerekebilir bunlara da.

2017-02-01 19:42 UTC, onuar commented on CONTRIBUTING.md
>  - Atanmış bir issue ile ilgili yardımcı olabilecekseniz issue sahibi ile iletişim geçilmelisiniz.
"iletişime geçebilirsiniz."

2017-02-01 19:42 UTC, onuar commented on CONTRIBUTING.md
> +- Teknik terimlerin çevirisinde bir bütünlük sağlamak amacı ile bir [sözlük](GLOSSARY.md) oluşturulmaktadır. Lütfen çevirinizi yaparken ve bir Pull Request'i incelerken bu sözlükte yer alan terimleri
Pull request'i küçük harflerle yazalım.

2017-02-01 19:42 UTC, onuar commented on CONTRIBUTING.md
> +- Yaptığınız değişiklik *push* yapmadan önce **git pull** komutunu kullanarak *upstream* i lokalinize indirin.
"değişikliği"

2017-02-01 19:42 UTC, onuar commented on CONTRIBUTING.md
> +- Yaptığınız değişiklik *push* yapmadan önce **git pull** komutunu kullanarak *upstream* i lokalinize indirin.
Push işlemini ve upstream işlemini ayrıca yazabiliriz. Git deneyimi olmayan arkadaşlar için, upstream ekleme işlemi her push'tan önce yapılan bir işlem gibi algılanabilir.

2017-02-02 18:55 UTC, ozgend requested changes

2017-02-02 18:55 UTC, ozgend commented on CONTRIBUTING.md
> +- Değişikliklerinizi yaptıktan sonra uygun **commit mesajı** ile değiğikliklerinizi *commit* yapın.
Ğ/Ş -> değişikliklerinizi

2017-02-02 18:55 UTC, ozgend commented on CONTRIBUTING.md
>  - Atanmış bir issue ile ilgili yardımcı olabilecekseniz issue sahibi ile iletişim geçilmelisiniz.
"iletişime geçmelisiniz"

2017-02-02 18:55 UTC, ozgend commented on CONTRIBUTING.md
> +- Değişikliklerinizi yaptıktan sonra uygun **commit mesajı** ile değiğikliklerinizi *commit* yapın.
Ğ/Ş -> değişikliklerinizi

2017-02-04 17:04 UTC, ozgend approved these changes

2017-02-04 17:04 UTC, merged