#4 Future JavaScript Now - Classes cevirisi tamamlandi
CodeFiction/typescript-book pull request #41
Opened 2017-02-14 10:09 UTC by mustafadinler

2017-02-14 13:11 UTC, ozgunbal requested changes
@mustafadinler 4'ü de birleşince büyük bir commit olmuş. Okurken yoruldum :D Gördüklerimi yazdım ama gözden kaçanlar da olmuş olabilir. Bu PR özelinde bi reviewer daha olması fena olmaz diye düşünüyorum.

2017-02-14 13:11 UTC, ozgunbal commented on docs/classes-extensibility.md
> +İnsanlar sıklıkla diğer JavaScript kitaplıklarındaki sınıflara özellikler ekler. İşte basit bir JavaScript örneği:
library için bir yerde kütüphane, bir yerde kitaplık kullanılmış. Benim gönlüm kütüphaneden yana ama yine de tartışmaya açık :D

2017-02-14 13:11 UTC, ozgunbal commented on docs/classes-emit.md
> +#### IIFE Nedir Ne Değildir?
Bence araya virgül koymalıyız. "nedir, ne değildir?

2017-02-14 13:11 UTC, ozgunbal commented on docs/classes-emit.md
> +Sebebi  Anlık-Çağrılan Fonksiyon İfadesi (Immediately-Invoked Function Expression) (IIFE) ile sarmalanmıştır, yani:
"sebebi ... ile sarmalanmıştır" olmuş çeviri.  -> "Bunun sebebi ... ile sarmalanmasıdır" daha iyi

2017-02-14 13:11 UTC, ozgunbal commented on docs/classes-emit.md
> +Şunu farkedeceksiniz ki bir sınıftan kalıtım yaptığınız anda TypeScript ayrıca aşağıdaki fonksiyonu da oluşturur:
farkedeceksiniz -> fark edeceksiniz
"inherit" için "kalıtım yapmak" dışında bir alternatif olabilir mi acaba? Aklıma bir şey gelmedi ama okurken çok bir şey ifade etmedi kalıtım yapmak.

2017-02-14 13:11 UTC, ozgunbal commented on docs/classes-emit.md
> +1. `d.prototype.__proto__ = b.prototype` yani etkin biçimde, alt sınıfının fonksiyonlarının prototiplerini isteğe bağlı olarak arama elemanlarına üst sınıfının `proto`'ları üzerinde atama yapar
Bence pek anlaşılır olmamış. Burası için önerisi olan var mı?

2017-02-14 13:11 UTC, ozgunbal commented on docs/classes-emit.md
> +Birçok insana bu konuyu anlattıktan sonra aşağıdaki açıklamayı en basit buluyorum. Öncelikle `__extends`'deki kodun nasıl basit `d.prototype.__proto__ = b.prototype`'a eşit olduğunu açıklayacağız, ve
"aşağıdaki açıklamayı en basit buluyorum" -> "aşağıdaki açıklamanın en basiti olduğunu düşünüyorum"
değerli -> önemli  (değerli daha çok ölçülebilir nicelikler için kullanıyor olması lazım)

2017-02-14 13:11 UTC, ozgunbal commented on docs/classes-emit.md
> +JavaScript'teki tüm nesneler `__proto__` elemanını içerir. Bu eleman eski tarayıcılar tarafından sıklıkla erişilemez durumdadır (bazen dökümantasyon bu sihirli özelliği `[[prototype]]` olarak ifade e
ikiside -> ikisi de
"neden destek dediğini açıkları" -> "neden destek verdiğini açıklar"
 "bu aşağıdaki ..." -> "Chrome konsolunda veya nodejs'te çalışabilen bir örneği aşağıda gösterilmiştir:"

2017-02-14 13:11 UTC, ozgunbal commented on docs/classes-emit.md
> +`__proto__`'yu anlıyorsun harika. Başka bir yararlı bilgi ise, JavaScript içerisindeki tüm `fonksiyon`'lar `prototype` diye adlandırılan özelliğe sahiptir ve fonksiyonu geri işaret eden `constructor`
anlıyorsun'dan sonra virgül lazım.
Sanki "pointing back"'in orada kendisini işaret eden gibi bir kullanımı var.

2017-02-14 13:11 UTC, ozgunbal commented on docs/classes-emit.md
> +Şimdi öğrenmeniz gereken diğer son şey ise,fonksiyon üzerinde `new`'ı çağırmak, fonksiyon çağrısından dönen yeni yaratılmış nesnenin `__proto__`'su içindeki `prototype`'ı kopyalar. İşte çalıştırıp ta
"diğer son şey" yerine hangisi uygunsa "diğer bir şey" veya "son bir şey" daha iyi gibi.
virgülden sonra boşluk

2017-02-14 13:11 UTC, ozgunbal commented on docs/classes-emit.md
> +#### `d.prototype.__proto__ = b.prototype` değeri
value gibi anlaşılıyor, "önemi", "olmasının önemi" vb.

2017-02-14 13:11 UTC, ozgunbal commented on docs/classes-emit.md
> +Değer şu ki, bu sizin fonksiyon elemanlarınızı alt sınıfa eklemenize ve diğerlerini üst sınıflardan almanıza izin verir. Bunun gösterimi aşağıdaki basit örnekte yapılmıştır:
Değer -> önem

2017-02-14 13:11 UTC, ozgunbal commented on docs/classes-emit.md
> +Aslında `bird.fly` `bird.__proto__.fly`'da aranacaktır (remember that `new`'ın `bird.__proto__`'nun `Bird.prototype`'u işaret ettireceğini hatırlayın) ve `bird.walk` (türetilen eleman) `bird.__proto_
"remember that" orada kalmış.

2017-02-14 13:11 UTC, ozgunbal commented on docs/classes.md
> +2. Geliştiricilere, kendi sürümleriyle gelen frameworkler (emberjs,reactjs etc) yerine, sınıfları kullanabilmeleri için tutarlı bir yöntem sağlar.
framework için bir çeviri önerilebilir. Ya da glossary'de bir karşılığı en azından.

2017-02-14 13:11 UTC, ozgunbal commented on docs/classes.md
> +Şimdi bu, birinci sınıf dil yapısı olarak yeterince deyimsel bir geleneksel JavaScript sınıfı kalıbıdır.
deyimsel'i kaldırsak mı? türkçede sırıtmış sanki.

2017-02-14 13:11 UTC, ozgunbal commented on docs/classes.md
> +Her zaman olduğu gibi, bu belirleyiciler hem eleman özellikleri hem de eleman fonksiyonları için çalışır.
modifier'a değiştirici desek daha iyi olmaz mı?

2017-02-14 13:11 UTC, ozgunbal commented on docs/classes.md
> +    members = [];  // Direk olarak yüklenir
direk -> direkt ya da doğrudan

2017-02-14 13:25 UTC, mustafadinler commented on docs/classes-extensibility.md
> +İnsanlar sıklıkla diğer JavaScript kitaplıklarındaki sınıflara özellikler ekler. İşte basit bir JavaScript örneği:
Bencede kutuphane o sekilde guncelleyecegim

2017-02-14 13:26 UTC, mustafadinler commented on docs/classes-emit.md
> +Şunu farkedeceksiniz ki bir sınıftan kalıtım yaptığınız anda TypeScript ayrıca aşağıdaki fonksiyonu da oluşturur:
turemek veya turetmek nasil olur?

2017-02-14 13:30 UTC, mustafadinler commented on docs/classes.md
> +Her zaman olduğu gibi, bu belirleyiciler hem eleman özellikleri hem de eleman fonksiyonları için çalışır.
aslinda olabilir ama bu gune kadar okudugum cok turkce makalede hep erisim belirleyici olarak kullanilmisti. Ben cok benimsemis olabilrim o yuzden tartisalim.

2017-02-14 13:33 UTC, mustafadinler commented on docs/classes-emit.md
> +1. `d.prototype.__proto__ = b.prototype` yani etkin biçimde, alt sınıfının fonksiyonlarının prototiplerini isteğe bağlı olarak arama elemanlarına üst sınıfının `proto`'ları üzerinde atama yapar
Burada cift tirnak icerisindeki esitligi acikliyor. Benimde pek icime sinmedi destek lazim:)

2017-02-14 13:47 UTC, ozgunbal commented on docs/classes-emit.md
> +Şunu farkedeceksiniz ki bir sınıftan kalıtım yaptığınız anda TypeScript ayrıca aşağıdaki fonksiyonu da oluşturur:
daha iyi bence. 
"Şunu fark edeceksiniz ki bir sınıftan alt bir sınıf türettiğinizde Typescript...." olabilir.

2017-02-14 13:49 UTC, ozgunbal commented on docs/classes.md
> +Her zaman olduğu gibi, bu belirleyiciler hem eleman özellikleri hem de eleman fonksiyonları için çalışır.
literatürü bilmiyorum açıkçası, doğru kullanım oysa glossary'de görmek lazım :smile:

2017-02-17 12:32 UTC, ozgunbal approved these changes
değişiklikler güzel olmuş. yine de başka bir göz daha baksın bu çeviriye diyorum.

2017-02-18 12:34 UTC, Blind-Striker approved these changes

2017-02-18 12:35 UTC, merged