#45 Common Errors çevirisi
CodeFiction/typescript-book pull request #47
Opened 2017-03-03 08:50 UTC by mustafadinler

2017-03-03 18:19 UTC, uguratar requested changes

2017-03-03 18:19 UTC, uguratar commented on docs/errors/main.md
> +Muhtemelen *modül* ([modüllere (modules) dair dahası][modules]) olarak üçüncü parti bir kütüphane (örneğin underscore) kullanıyorsunuz ve bunun için içsel deklarasyon dosyanız yok ([içsel deklarasyon
Bence şöyle çevirmek daha doğru olabilir;
Muhtemelen üçüncü parti bir kütüphaneyi *modül* ([modüllere dair daha fazla bilgi][modules]) olarak  (örneğin underscore) kullanıyorsunuz ve bunun için içsel deklarasyon dosyanız yok ([içsel deklarasyona dair daha fazla bilgi][ambient]).

2017-03-03 18:19 UTC, uguratar commented on docs/errors/main.md
> +# Genel Hatalar
*Genel Hatalar* demek yerine *Sıkça Karşılaşılan Hatalar* demek daha doğru olur mu?

2017-03-03 18:19 UTC, uguratar commented on docs/errors/main.md
> +Muhtemelen `declare (deklare)` etmediğiniz üçüncü parti bir kütüphane (örneğin google analytics) kullanıyorsunuz. TypeScript sizi *yazım hatalarından* ve *değişkenleri deklare etmeden kullanmanızdan*
Bence şu şekil daha doğru linkler için;
([nasıl düzeltileceğine dair daha fazla bilgi][ambient])

2017-03-04 12:39 UTC, mustafadinler commented on docs/errors/main.md
> +# Genel Hatalar
Güzel olur düzletiyorum.

2017-03-04 12:50 UTC, uguratar approved these changes

2017-03-04 12:51 UTC, uguratar commented
@mustafadinler ellere sağlık, bana kalırsa gayet güzel olmuş.

2017-03-04 13:39 UTC, ozgunbal commented on docs/errors/main.md
> +Muhtemelen `deklare (declare)` etmediğiniz üçüncü parti bir kütüphane (örneğin google analytics) kullanıyorsunuz. TypeScript sizi *yazım hatalarından* ve *değişkenleri deklare etmeden kullanmanızdan*
deklare yerine tanımlamak kullanılabilir, kulağa nasıl geliyor. Çoğu kaynak "declare a variable" yerine değişken tanımlamak kullanıyor.

2017-03-04 13:40 UTC, ozgunbal commented on docs/errors/main.md
> +Muhtemelen üçüncü parti bir kütüphaneyi (örneğin underscore) *modül* ([modüllere (modules) dair daha fazla bilgi][modules]) olarak kullanıyorsunuz ve bunun için içsel deklarasyon dosyanız yok ([çsel
aynı şekilde deklarasyon yerine tanımlama/tanım kullanılabilir. 
Bir de paratez içinde çsel -> içsel

2017-03-05 10:19 UTC, mustafadinler commented on docs/errors/main.md
> +Muhtemelen `deklare (declare)` etmediğiniz üçüncü parti bir kütüphane (örneğin google analytics) kullanıyorsunuz. TypeScript sizi *yazım hatalarından* ve *değişkenleri deklare etmeden kullanmanızdan*
aslinda bana kalirsa declare ve define arasinda fark var gibi geliyo. Arkadaslar yorum yaparsa degistiririm.

2017-03-05 17:05 UTC, DorukUlucay commented on docs/errors/main.md
> +Muhtemelen `deklare (declare)` etmediğiniz üçüncü parti bir kütüphane (örneğin google analytics) kullanıyorsunuz. TypeScript sizi *yazım hatalarından* ve *değişkenleri deklare etmeden kullanmanızdan*
bildiğim kadarıyla declare
`int a;`

define:
`int a = 100;`

yani **declare**'i, _deklare etmek_, **define**'ı, _tanımlamak_ şeklinde kullanmak daha mantıklı gibi.

2017-03-06 10:17 UTC, ozgunbal approved these changes
Tamamdır, eline sağlık.

2017-03-06 10:18 UTC, merged