Namespaces çevirisi
CodeFiction/typescript-book pull request #65
Opened 2017-09-23 23:19 UTC by uguratar

2017-09-24 00:11 UTC, onuar requested changes

2017-09-24 00:11 UTC, onuar commented on docs/project/namespaces.md
> +## Aduzayları (Namespaces)
Uğur, aduzayları çevirini [glossary.md](https://github.com/CodeFiction/typescript-book/blob/master/GLOSSARY.md)'ye de ekler misin?

2017-09-24 00:11 UTC, onuar commented on docs/project/namespaces.md
> +Örnek proje oluştururken veya eski JavaScript kodunu port ederken  harici modül ve `namespace` kullanımı tavsiye edilmektedir.
"ederken  harici" arası fazla boşluk.

2017-09-24 09:17 UTC, uguratar commented on docs/project/namespaces.md
> +## Aduzayları (Namespaces)
Ekledim @onuar, atlamışım.

2017-09-24 09:18 UTC, uguratar commented on docs/project/namespaces.md
> +Örnek proje oluştururken veya eski JavaScript kodunu port ederken  harici modül ve `namespace` kullanımı tavsiye edilmektedir.
Eye for detail :)

2017-09-24 09:19 UTC, uguratar commented
@onuar hallolmuş olmalı şimdi, tekrar review alabilir miyim?

2017-09-25 21:17 UTC, msusur approved these changes

2017-09-26 09:12 UTC, onuar approved these changes

2017-09-26 09:13 UTC, onuar commented
Eline sağlık abi.

2017-09-26 09:13 UTC, merged